/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowpp (void);
GtkWidget* create_windowajout (void);
GtkWidget* create_windowmodif (void);
GtkWidget* create_windowstat (void);
